import test;

hello_world();

// @["test"]
// hello_world();

// Test an on-statement
#[loc("test")]
{
    println("I'm talking to you from far away!");
    hello_world();
}

let random := "random";
{
    #![loc("random_but_not_really_anymore")]
    println("I have no idea where I am!");
    hello_world();
}

func fourty_two() {
    return "42";
}
#[loc("42")]
{
    println("I have found the answer");
    hello_world();
}
